CLASS zcl_lab_12_linux_ga DEFINITION INHERITING FROM zcl_lab_11_system_ga
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_12_linux_ga IMPLEMENTATION.
ENDCLASS.
