CLASS zcl_lab_39_budget_ga DEFINITION ABSTRACT
  PUBLIC
  "FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  METHODS get_budget ABSTRACT RETURNING VALUE(rv_budget) TYPE i.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_39_budget_ga IMPLEMENTATION.
ENDCLASS.
